### ISSUE TITLE
Deploy CICD Github Action on demand 

### ISSUE THREAD

**Issue by RobertCzaja** [RobertCzaja/it-offers-api#38]
* https://ardalis.com/github-actions-on-demand/

**Comment by RobertCzaja** [comment]
GitHub Actions also allows manual triggering of specific steps in a pipeline, but it requires proper workflow configuration. Below is an explanation of how it works:

# 1. Manual Workflow Triggers
GitHub Actions supports manually triggering entire workflows using the workflow_dispatch event. You can define a workflow that can be run manually from the GitHub interface.

Example configuration:
```
name: Manual Trigger Example

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to ${{ inputs.environment }}
        run: echo "Deploying to ${{ inputs.environment }}"
```
Once configured, this workflow can be manually triggered from the Actions tab in your GitHub repository.

# 2. Blocking Specific Steps
To enable certain steps to run only upon manual approval, you can use:

Conditional steps: Steps can be conditionally executed based on input parameters.
Environment protection rules: GitHub allows you to configure environments with protection rules, such as requiring manual approval before a workflow can proceed.
Example using environment protection rules:

Set up an environment in your GitHub repository under Settings > Environments.
Add protection rules, such as requiring manual approval before the workflow runs.
Workflow using a protected environment:

```
name: Protected Environment Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to production
        run: echo "Deploying to production"
```
# 3. Dynamic Stages (Reusable Workflows)
If you want individual steps to be triggered independently, you can split your workflow into smaller parts and use Reusable Workflows. Each reusable workflow can be triggered manually.

Example of calling another workflow:

```
name: Call Reusable Workflow

on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: owner/repo/.github/workflows/reusable-workflow.yml@main
    with:
      environment: production
```
# Summary
GitHub Actions allows manual workflow triggering using workflow_dispatch, blocking stages through environment protection rules, and modular configurations with reusable workflows. This provides great flexibility in setting up pipelines.
